{"uuid": "3e6da982-c824-460b-be58-32a42ca61e55", "children": ["50632de8-09fa-44e2-a72a-fa0c9ca02ec1"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\n", "trace": "  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/conftest.py\", line 36, in driver\n    request.cls.driver = webdriver.Remote(url, capabilities)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 274, in __init__\n    super().__init__(\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 266, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/appium/webdriver/webdriver.py\", line 369, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/rucindrea/workspace/courses/AltTicTacToe/AltTicTacToeInstrumented/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1646329655475, "stop": 1646329655503}], "start": 1646329655475, "stop": 1646329655631}